language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install codecov
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest
  - coverage run -m pytest

after_success:
  - codecov